name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04
    steps:
      - name: Install utils
        run: (sudo apt update && sudo apt install -y llvm-11-dev)

      - name: Clone nballerina repository
        id : cache-nballerina
        uses: actions/checkout@v2

      - name: nballerina compiler
        run: (cd "$GITHUB_WORKSPACE/build" && cmake -DCMAKE_BUILD_TYPE="Release" ../ && make)
